apiVersion: v1
kind: Pod
metadata:
  name: cart-app-pod
  namespace: praveen-ns
spec:
  containers:
    - name: test-containers
      image: mepsk29/sre-test-image:1.0
      ports:
        - containerPort: 3015